//
//  MapInteractor.swift
//  Foorun
//
//  Created by 김나희 on 9/28/22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol MapBusinessLogic {
    func loadAnnotations(request: Map.FetchAnnotations.Request)
}

final class MapInteractor {
    var mapPresenter: MapPresentationLogic?
    var mapWorker: MapWorker?
}

extension MapInteractor: MapBusinessLogic {
    func loadAnnotations(request: Map.FetchAnnotations.Request) {
        mapWorker = MapWorker()
        mapWorker?.fetchAnnotations(latitude: request.coordinate.latitude, longitude: request.coordinate.longitude) { data in
            let response = Map.FetchAnnotations.Response(annotations: data)
            self.mapPresenter?.presentAnnotations(response: response)
        }
    }
}
