//
//  MapModels.swift
//  Foorun
//
//  Created by 김나희 on 9/28/22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import CoreLocation
import UIKit

enum Map {
    enum FetchAnnotations {
        struct Request {
            let coordinate: CLLocationCoordinate2D
        }
        struct Response {
            let annotations: [Annotation]
        }
        struct ViewModel {
            let displayedAnnotations: [DisplayedAnnotation]
        }
    }
}
