//
//  MapPresenter.swift
//  Foorun
//
//  Created by 김나희 on 9/28/22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol MapPresentationLogic {
    func presentAnnotations(response: Map.FetchAnnotations.Response)
}

final class MapPresenter: MapPresentationLogic {
    weak var viewController: MapDisplayLogic?
        
    func presentAnnotations(response: Map.FetchAnnotations.Response) {
        let viewModel = Map.FetchAnnotations.ViewModel(displayedAnnotations: response.annotations.map { $0.toDomain() })
        viewController?.displayAnnotations(viewModel: viewModel)
    }
}
